// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: App.proto

package uc.mei.is;

public interface ProtoProfListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tutorial.ProtoProfList)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .tutorial.ProtoProfessor professor = 1;</code>
   */
  java.util.List<uc.mei.is.ProtoProfessor> 
      getProfessorList();
  /**
   * <code>repeated .tutorial.ProtoProfessor professor = 1;</code>
   */
  uc.mei.is.ProtoProfessor getProfessor(int index);
  /**
   * <code>repeated .tutorial.ProtoProfessor professor = 1;</code>
   */
  int getProfessorCount();
  /**
   * <code>repeated .tutorial.ProtoProfessor professor = 1;</code>
   */
  java.util.List<? extends uc.mei.is.ProtoProfessorOrBuilder> 
      getProfessorOrBuilderList();
  /**
   * <code>repeated .tutorial.ProtoProfessor professor = 1;</code>
   */
  uc.mei.is.ProtoProfessorOrBuilder getProfessorOrBuilder(
      int index);
}
