// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: App.proto

package uc.mei.is;

public interface ProtoStudentOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tutorial.ProtoStudent)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string uuid = 1;</code>
   * @return Whether the uuid field is set.
   */
  boolean hasUuid();
  /**
   * <code>optional string uuid = 1;</code>
   * @return The uuid.
   */
  java.lang.String getUuid();
  /**
   * <code>optional string uuid = 1;</code>
   * @return The bytes for uuid.
   */
  com.google.protobuf.ByteString
      getUuidBytes();

  /**
   * <code>optional string name = 2;</code>
   * @return Whether the name field is set.
   */
  boolean hasName();
  /**
   * <code>optional string name = 2;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>optional string name = 2;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>optional string phoneNum = 3;</code>
   * @return Whether the phoneNum field is set.
   */
  boolean hasPhoneNum();
  /**
   * <code>optional string phoneNum = 3;</code>
   * @return The phoneNum.
   */
  java.lang.String getPhoneNum();
  /**
   * <code>optional string phoneNum = 3;</code>
   * @return The bytes for phoneNum.
   */
  com.google.protobuf.ByteString
      getPhoneNumBytes();

  /**
   * <code>optional string addr = 4;</code>
   * @return Whether the addr field is set.
   */
  boolean hasAddr();
  /**
   * <code>optional string addr = 4;</code>
   * @return The addr.
   */
  java.lang.String getAddr();
  /**
   * <code>optional string addr = 4;</code>
   * @return The bytes for addr.
   */
  com.google.protobuf.ByteString
      getAddrBytes();

  /**
   * <code>optional .google.protobuf.Timestamp bday = 5;</code>
   * @return Whether the bday field is set.
   */
  boolean hasBday();
  /**
   * <code>optional .google.protobuf.Timestamp bday = 5;</code>
   * @return The bday.
   */
  com.google.protobuf.Timestamp getBday();
  /**
   * <code>optional .google.protobuf.Timestamp bday = 5;</code>
   */
  com.google.protobuf.TimestampOrBuilder getBdayOrBuilder();

  /**
   * <code>optional string profuuid = 6;</code>
   * @return Whether the profuuid field is set.
   */
  boolean hasProfuuid();
  /**
   * <code>optional string profuuid = 6;</code>
   * @return The profuuid.
   */
  java.lang.String getProfuuid();
  /**
   * <code>optional string profuuid = 6;</code>
   * @return The bytes for profuuid.
   */
  com.google.protobuf.ByteString
      getProfuuidBytes();

  /**
   * <code>optional string gender = 7;</code>
   * @return Whether the gender field is set.
   */
  boolean hasGender();
  /**
   * <code>optional string gender = 7;</code>
   * @return The gender.
   */
  java.lang.String getGender();
  /**
   * <code>optional string gender = 7;</code>
   * @return The bytes for gender.
   */
  com.google.protobuf.ByteString
      getGenderBytes();

  /**
   * <code>optional .google.protobuf.Timestamp registrationDate = 8;</code>
   * @return Whether the registrationDate field is set.
   */
  boolean hasRegistrationDate();
  /**
   * <code>optional .google.protobuf.Timestamp registrationDate = 8;</code>
   * @return The registrationDate.
   */
  com.google.protobuf.Timestamp getRegistrationDate();
  /**
   * <code>optional .google.protobuf.Timestamp registrationDate = 8;</code>
   */
  com.google.protobuf.TimestampOrBuilder getRegistrationDateOrBuilder();
}
