// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: App.proto

package uc.mei.is;

/**
 * Protobuf type {@code tutorial.ProtoProfessor}
 */
public final class ProtoProfessor extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:tutorial.ProtoProfessor)
    ProtoProfessorOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ProtoProfessor.newBuilder() to construct.
  private ProtoProfessor(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ProtoProfessor() {
    uuid_ = "";
    name_ = "";
    phoneNum_ = "";
    addr_ = "";
    student_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ProtoProfessor();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ProtoProfessor(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();
            bitField0_ |= 0x00000001;
            uuid_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();
            bitField0_ |= 0x00000002;
            name_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();
            bitField0_ |= 0x00000004;
            phoneNum_ = s;
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();
            bitField0_ |= 0x00000008;
            addr_ = s;
            break;
          }
          case 42: {
            com.google.protobuf.Timestamp.Builder subBuilder = null;
            if (((bitField0_ & 0x00000010) != 0)) {
              subBuilder = bday_.toBuilder();
            }
            bday_ = input.readMessage(com.google.protobuf.Timestamp.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(bday_);
              bday_ = subBuilder.buildPartial();
            }
            bitField0_ |= 0x00000010;
            break;
          }
          case 50: {
            if (!((mutable_bitField0_ & 0x00000020) != 0)) {
              student_ = new java.util.ArrayList<uc.mei.is.ProtoStudent>();
              mutable_bitField0_ |= 0x00000020;
            }
            student_.add(
                input.readMessage(uc.mei.is.ProtoStudent.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (com.google.protobuf.UninitializedMessageException e) {
      throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000020) != 0)) {
        student_ = java.util.Collections.unmodifiableList(student_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return uc.mei.is.ProtoApp.internal_static_tutorial_ProtoProfessor_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return uc.mei.is.ProtoApp.internal_static_tutorial_ProtoProfessor_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            uc.mei.is.ProtoProfessor.class, uc.mei.is.ProtoProfessor.Builder.class);
  }

  private int bitField0_;
  public static final int UUID_FIELD_NUMBER = 1;
  private volatile java.lang.Object uuid_;
  /**
   * <code>optional string uuid = 1;</code>
   * @return Whether the uuid field is set.
   */
  @java.lang.Override
  public boolean hasUuid() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>optional string uuid = 1;</code>
   * @return The uuid.
   */
  @java.lang.Override
  public java.lang.String getUuid() {
    java.lang.Object ref = uuid_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      uuid_ = s;
      return s;
    }
  }
  /**
   * <code>optional string uuid = 1;</code>
   * @return The bytes for uuid.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getUuidBytes() {
    java.lang.Object ref = uuid_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      uuid_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int NAME_FIELD_NUMBER = 2;
  private volatile java.lang.Object name_;
  /**
   * <code>optional string name = 2;</code>
   * @return Whether the name field is set.
   */
  @java.lang.Override
  public boolean hasName() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>optional string name = 2;</code>
   * @return The name.
   */
  @java.lang.Override
  public java.lang.String getName() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      name_ = s;
      return s;
    }
  }
  /**
   * <code>optional string name = 2;</code>
   * @return The bytes for name.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNameBytes() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PHONENUM_FIELD_NUMBER = 3;
  private volatile java.lang.Object phoneNum_;
  /**
   * <code>optional string phoneNum = 3;</code>
   * @return Whether the phoneNum field is set.
   */
  @java.lang.Override
  public boolean hasPhoneNum() {
    return ((bitField0_ & 0x00000004) != 0);
  }
  /**
   * <code>optional string phoneNum = 3;</code>
   * @return The phoneNum.
   */
  @java.lang.Override
  public java.lang.String getPhoneNum() {
    java.lang.Object ref = phoneNum_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      phoneNum_ = s;
      return s;
    }
  }
  /**
   * <code>optional string phoneNum = 3;</code>
   * @return The bytes for phoneNum.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getPhoneNumBytes() {
    java.lang.Object ref = phoneNum_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      phoneNum_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ADDR_FIELD_NUMBER = 4;
  private volatile java.lang.Object addr_;
  /**
   * <code>optional string addr = 4;</code>
   * @return Whether the addr field is set.
   */
  @java.lang.Override
  public boolean hasAddr() {
    return ((bitField0_ & 0x00000008) != 0);
  }
  /**
   * <code>optional string addr = 4;</code>
   * @return The addr.
   */
  @java.lang.Override
  public java.lang.String getAddr() {
    java.lang.Object ref = addr_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      addr_ = s;
      return s;
    }
  }
  /**
   * <code>optional string addr = 4;</code>
   * @return The bytes for addr.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getAddrBytes() {
    java.lang.Object ref = addr_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      addr_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int BDAY_FIELD_NUMBER = 5;
  private com.google.protobuf.Timestamp bday_;
  /**
   * <code>optional .google.protobuf.Timestamp bday = 5;</code>
   * @return Whether the bday field is set.
   */
  @java.lang.Override
  public boolean hasBday() {
    return ((bitField0_ & 0x00000010) != 0);
  }
  /**
   * <code>optional .google.protobuf.Timestamp bday = 5;</code>
   * @return The bday.
   */
  @java.lang.Override
  public com.google.protobuf.Timestamp getBday() {
    return bday_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : bday_;
  }
  /**
   * <code>optional .google.protobuf.Timestamp bday = 5;</code>
   */
  @java.lang.Override
  public com.google.protobuf.TimestampOrBuilder getBdayOrBuilder() {
    return bday_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : bday_;
  }

  public static final int STUDENT_FIELD_NUMBER = 6;
  private java.util.List<uc.mei.is.ProtoStudent> student_;
  /**
   * <code>repeated .tutorial.ProtoStudent student = 6;</code>
   */
  @java.lang.Override
  public java.util.List<uc.mei.is.ProtoStudent> getStudentList() {
    return student_;
  }
  /**
   * <code>repeated .tutorial.ProtoStudent student = 6;</code>
   */
  @java.lang.Override
  public java.util.List<? extends uc.mei.is.ProtoStudentOrBuilder> 
      getStudentOrBuilderList() {
    return student_;
  }
  /**
   * <code>repeated .tutorial.ProtoStudent student = 6;</code>
   */
  @java.lang.Override
  public int getStudentCount() {
    return student_.size();
  }
  /**
   * <code>repeated .tutorial.ProtoStudent student = 6;</code>
   */
  @java.lang.Override
  public uc.mei.is.ProtoStudent getStudent(int index) {
    return student_.get(index);
  }
  /**
   * <code>repeated .tutorial.ProtoStudent student = 6;</code>
   */
  @java.lang.Override
  public uc.mei.is.ProtoStudentOrBuilder getStudentOrBuilder(
      int index) {
    return student_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, uuid_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, phoneNum_);
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, addr_);
    }
    if (((bitField0_ & 0x00000010) != 0)) {
      output.writeMessage(5, getBday());
    }
    for (int i = 0; i < student_.size(); i++) {
      output.writeMessage(6, student_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, uuid_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, phoneNum_);
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, addr_);
    }
    if (((bitField0_ & 0x00000010) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, getBday());
    }
    for (int i = 0; i < student_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(6, student_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof uc.mei.is.ProtoProfessor)) {
      return super.equals(obj);
    }
    uc.mei.is.ProtoProfessor other = (uc.mei.is.ProtoProfessor) obj;

    if (hasUuid() != other.hasUuid()) return false;
    if (hasUuid()) {
      if (!getUuid()
          .equals(other.getUuid())) return false;
    }
    if (hasName() != other.hasName()) return false;
    if (hasName()) {
      if (!getName()
          .equals(other.getName())) return false;
    }
    if (hasPhoneNum() != other.hasPhoneNum()) return false;
    if (hasPhoneNum()) {
      if (!getPhoneNum()
          .equals(other.getPhoneNum())) return false;
    }
    if (hasAddr() != other.hasAddr()) return false;
    if (hasAddr()) {
      if (!getAddr()
          .equals(other.getAddr())) return false;
    }
    if (hasBday() != other.hasBday()) return false;
    if (hasBday()) {
      if (!getBday()
          .equals(other.getBday())) return false;
    }
    if (!getStudentList()
        .equals(other.getStudentList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasUuid()) {
      hash = (37 * hash) + UUID_FIELD_NUMBER;
      hash = (53 * hash) + getUuid().hashCode();
    }
    if (hasName()) {
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
    }
    if (hasPhoneNum()) {
      hash = (37 * hash) + PHONENUM_FIELD_NUMBER;
      hash = (53 * hash) + getPhoneNum().hashCode();
    }
    if (hasAddr()) {
      hash = (37 * hash) + ADDR_FIELD_NUMBER;
      hash = (53 * hash) + getAddr().hashCode();
    }
    if (hasBday()) {
      hash = (37 * hash) + BDAY_FIELD_NUMBER;
      hash = (53 * hash) + getBday().hashCode();
    }
    if (getStudentCount() > 0) {
      hash = (37 * hash) + STUDENT_FIELD_NUMBER;
      hash = (53 * hash) + getStudentList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static uc.mei.is.ProtoProfessor parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static uc.mei.is.ProtoProfessor parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static uc.mei.is.ProtoProfessor parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static uc.mei.is.ProtoProfessor parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static uc.mei.is.ProtoProfessor parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static uc.mei.is.ProtoProfessor parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static uc.mei.is.ProtoProfessor parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static uc.mei.is.ProtoProfessor parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static uc.mei.is.ProtoProfessor parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static uc.mei.is.ProtoProfessor parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static uc.mei.is.ProtoProfessor parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static uc.mei.is.ProtoProfessor parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(uc.mei.is.ProtoProfessor prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code tutorial.ProtoProfessor}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:tutorial.ProtoProfessor)
      uc.mei.is.ProtoProfessorOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return uc.mei.is.ProtoApp.internal_static_tutorial_ProtoProfessor_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return uc.mei.is.ProtoApp.internal_static_tutorial_ProtoProfessor_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              uc.mei.is.ProtoProfessor.class, uc.mei.is.ProtoProfessor.Builder.class);
    }

    // Construct using uc.mei.is.ProtoProfessor.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getBdayFieldBuilder();
        getStudentFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      uuid_ = "";
      bitField0_ = (bitField0_ & ~0x00000001);
      name_ = "";
      bitField0_ = (bitField0_ & ~0x00000002);
      phoneNum_ = "";
      bitField0_ = (bitField0_ & ~0x00000004);
      addr_ = "";
      bitField0_ = (bitField0_ & ~0x00000008);
      if (bdayBuilder_ == null) {
        bday_ = null;
      } else {
        bdayBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000010);
      if (studentBuilder_ == null) {
        student_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000020);
      } else {
        studentBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return uc.mei.is.ProtoApp.internal_static_tutorial_ProtoProfessor_descriptor;
    }

    @java.lang.Override
    public uc.mei.is.ProtoProfessor getDefaultInstanceForType() {
      return uc.mei.is.ProtoProfessor.getDefaultInstance();
    }

    @java.lang.Override
    public uc.mei.is.ProtoProfessor build() {
      uc.mei.is.ProtoProfessor result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public uc.mei.is.ProtoProfessor buildPartial() {
      uc.mei.is.ProtoProfessor result = new uc.mei.is.ProtoProfessor(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        to_bitField0_ |= 0x00000001;
      }
      result.uuid_ = uuid_;
      if (((from_bitField0_ & 0x00000002) != 0)) {
        to_bitField0_ |= 0x00000002;
      }
      result.name_ = name_;
      if (((from_bitField0_ & 0x00000004) != 0)) {
        to_bitField0_ |= 0x00000004;
      }
      result.phoneNum_ = phoneNum_;
      if (((from_bitField0_ & 0x00000008) != 0)) {
        to_bitField0_ |= 0x00000008;
      }
      result.addr_ = addr_;
      if (((from_bitField0_ & 0x00000010) != 0)) {
        if (bdayBuilder_ == null) {
          result.bday_ = bday_;
        } else {
          result.bday_ = bdayBuilder_.build();
        }
        to_bitField0_ |= 0x00000010;
      }
      if (studentBuilder_ == null) {
        if (((bitField0_ & 0x00000020) != 0)) {
          student_ = java.util.Collections.unmodifiableList(student_);
          bitField0_ = (bitField0_ & ~0x00000020);
        }
        result.student_ = student_;
      } else {
        result.student_ = studentBuilder_.build();
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof uc.mei.is.ProtoProfessor) {
        return mergeFrom((uc.mei.is.ProtoProfessor)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(uc.mei.is.ProtoProfessor other) {
      if (other == uc.mei.is.ProtoProfessor.getDefaultInstance()) return this;
      if (other.hasUuid()) {
        bitField0_ |= 0x00000001;
        uuid_ = other.uuid_;
        onChanged();
      }
      if (other.hasName()) {
        bitField0_ |= 0x00000002;
        name_ = other.name_;
        onChanged();
      }
      if (other.hasPhoneNum()) {
        bitField0_ |= 0x00000004;
        phoneNum_ = other.phoneNum_;
        onChanged();
      }
      if (other.hasAddr()) {
        bitField0_ |= 0x00000008;
        addr_ = other.addr_;
        onChanged();
      }
      if (other.hasBday()) {
        mergeBday(other.getBday());
      }
      if (studentBuilder_ == null) {
        if (!other.student_.isEmpty()) {
          if (student_.isEmpty()) {
            student_ = other.student_;
            bitField0_ = (bitField0_ & ~0x00000020);
          } else {
            ensureStudentIsMutable();
            student_.addAll(other.student_);
          }
          onChanged();
        }
      } else {
        if (!other.student_.isEmpty()) {
          if (studentBuilder_.isEmpty()) {
            studentBuilder_.dispose();
            studentBuilder_ = null;
            student_ = other.student_;
            bitField0_ = (bitField0_ & ~0x00000020);
            studentBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getStudentFieldBuilder() : null;
          } else {
            studentBuilder_.addAllMessages(other.student_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      uc.mei.is.ProtoProfessor parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (uc.mei.is.ProtoProfessor) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.lang.Object uuid_ = "";
    /**
     * <code>optional string uuid = 1;</code>
     * @return Whether the uuid field is set.
     */
    public boolean hasUuid() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional string uuid = 1;</code>
     * @return The uuid.
     */
    public java.lang.String getUuid() {
      java.lang.Object ref = uuid_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        uuid_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string uuid = 1;</code>
     * @return The bytes for uuid.
     */
    public com.google.protobuf.ByteString
        getUuidBytes() {
      java.lang.Object ref = uuid_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        uuid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string uuid = 1;</code>
     * @param value The uuid to set.
     * @return This builder for chaining.
     */
    public Builder setUuid(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
      uuid_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string uuid = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearUuid() {
      bitField0_ = (bitField0_ & ~0x00000001);
      uuid_ = getDefaultInstance().getUuid();
      onChanged();
      return this;
    }
    /**
     * <code>optional string uuid = 1;</code>
     * @param value The bytes for uuid to set.
     * @return This builder for chaining.
     */
    public Builder setUuidBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      bitField0_ |= 0x00000001;
      uuid_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object name_ = "";
    /**
     * <code>optional string name = 2;</code>
     * @return Whether the name field is set.
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional string name = 2;</code>
     * @return The name.
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string name = 2;</code>
     * @return The bytes for name.
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string name = 2;</code>
     * @param value The name to set.
     * @return This builder for chaining.
     */
    public Builder setName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
      name_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string name = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearName() {
      bitField0_ = (bitField0_ & ~0x00000002);
      name_ = getDefaultInstance().getName();
      onChanged();
      return this;
    }
    /**
     * <code>optional string name = 2;</code>
     * @param value The bytes for name to set.
     * @return This builder for chaining.
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      bitField0_ |= 0x00000002;
      name_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object phoneNum_ = "";
    /**
     * <code>optional string phoneNum = 3;</code>
     * @return Whether the phoneNum field is set.
     */
    public boolean hasPhoneNum() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional string phoneNum = 3;</code>
     * @return The phoneNum.
     */
    public java.lang.String getPhoneNum() {
      java.lang.Object ref = phoneNum_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        phoneNum_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string phoneNum = 3;</code>
     * @return The bytes for phoneNum.
     */
    public com.google.protobuf.ByteString
        getPhoneNumBytes() {
      java.lang.Object ref = phoneNum_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        phoneNum_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string phoneNum = 3;</code>
     * @param value The phoneNum to set.
     * @return This builder for chaining.
     */
    public Builder setPhoneNum(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
      phoneNum_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string phoneNum = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearPhoneNum() {
      bitField0_ = (bitField0_ & ~0x00000004);
      phoneNum_ = getDefaultInstance().getPhoneNum();
      onChanged();
      return this;
    }
    /**
     * <code>optional string phoneNum = 3;</code>
     * @param value The bytes for phoneNum to set.
     * @return This builder for chaining.
     */
    public Builder setPhoneNumBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      bitField0_ |= 0x00000004;
      phoneNum_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object addr_ = "";
    /**
     * <code>optional string addr = 4;</code>
     * @return Whether the addr field is set.
     */
    public boolean hasAddr() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>optional string addr = 4;</code>
     * @return The addr.
     */
    public java.lang.String getAddr() {
      java.lang.Object ref = addr_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        addr_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string addr = 4;</code>
     * @return The bytes for addr.
     */
    public com.google.protobuf.ByteString
        getAddrBytes() {
      java.lang.Object ref = addr_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        addr_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string addr = 4;</code>
     * @param value The addr to set.
     * @return This builder for chaining.
     */
    public Builder setAddr(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
      addr_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string addr = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearAddr() {
      bitField0_ = (bitField0_ & ~0x00000008);
      addr_ = getDefaultInstance().getAddr();
      onChanged();
      return this;
    }
    /**
     * <code>optional string addr = 4;</code>
     * @param value The bytes for addr to set.
     * @return This builder for chaining.
     */
    public Builder setAddrBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      bitField0_ |= 0x00000008;
      addr_ = value;
      onChanged();
      return this;
    }

    private com.google.protobuf.Timestamp bday_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> bdayBuilder_;
    /**
     * <code>optional .google.protobuf.Timestamp bday = 5;</code>
     * @return Whether the bday field is set.
     */
    public boolean hasBday() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <code>optional .google.protobuf.Timestamp bday = 5;</code>
     * @return The bday.
     */
    public com.google.protobuf.Timestamp getBday() {
      if (bdayBuilder_ == null) {
        return bday_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : bday_;
      } else {
        return bdayBuilder_.getMessage();
      }
    }
    /**
     * <code>optional .google.protobuf.Timestamp bday = 5;</code>
     */
    public Builder setBday(com.google.protobuf.Timestamp value) {
      if (bdayBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        bday_ = value;
        onChanged();
      } else {
        bdayBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000010;
      return this;
    }
    /**
     * <code>optional .google.protobuf.Timestamp bday = 5;</code>
     */
    public Builder setBday(
        com.google.protobuf.Timestamp.Builder builderForValue) {
      if (bdayBuilder_ == null) {
        bday_ = builderForValue.build();
        onChanged();
      } else {
        bdayBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000010;
      return this;
    }
    /**
     * <code>optional .google.protobuf.Timestamp bday = 5;</code>
     */
    public Builder mergeBday(com.google.protobuf.Timestamp value) {
      if (bdayBuilder_ == null) {
        if (((bitField0_ & 0x00000010) != 0) &&
            bday_ != null &&
            bday_ != com.google.protobuf.Timestamp.getDefaultInstance()) {
          bday_ =
            com.google.protobuf.Timestamp.newBuilder(bday_).mergeFrom(value).buildPartial();
        } else {
          bday_ = value;
        }
        onChanged();
      } else {
        bdayBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000010;
      return this;
    }
    /**
     * <code>optional .google.protobuf.Timestamp bday = 5;</code>
     */
    public Builder clearBday() {
      if (bdayBuilder_ == null) {
        bday_ = null;
        onChanged();
      } else {
        bdayBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000010);
      return this;
    }
    /**
     * <code>optional .google.protobuf.Timestamp bday = 5;</code>
     */
    public com.google.protobuf.Timestamp.Builder getBdayBuilder() {
      bitField0_ |= 0x00000010;
      onChanged();
      return getBdayFieldBuilder().getBuilder();
    }
    /**
     * <code>optional .google.protobuf.Timestamp bday = 5;</code>
     */
    public com.google.protobuf.TimestampOrBuilder getBdayOrBuilder() {
      if (bdayBuilder_ != null) {
        return bdayBuilder_.getMessageOrBuilder();
      } else {
        return bday_ == null ?
            com.google.protobuf.Timestamp.getDefaultInstance() : bday_;
      }
    }
    /**
     * <code>optional .google.protobuf.Timestamp bday = 5;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
        getBdayFieldBuilder() {
      if (bdayBuilder_ == null) {
        bdayBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                getBday(),
                getParentForChildren(),
                isClean());
        bday_ = null;
      }
      return bdayBuilder_;
    }

    private java.util.List<uc.mei.is.ProtoStudent> student_ =
      java.util.Collections.emptyList();
    private void ensureStudentIsMutable() {
      if (!((bitField0_ & 0x00000020) != 0)) {
        student_ = new java.util.ArrayList<uc.mei.is.ProtoStudent>(student_);
        bitField0_ |= 0x00000020;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        uc.mei.is.ProtoStudent, uc.mei.is.ProtoStudent.Builder, uc.mei.is.ProtoStudentOrBuilder> studentBuilder_;

    /**
     * <code>repeated .tutorial.ProtoStudent student = 6;</code>
     */
    public java.util.List<uc.mei.is.ProtoStudent> getStudentList() {
      if (studentBuilder_ == null) {
        return java.util.Collections.unmodifiableList(student_);
      } else {
        return studentBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .tutorial.ProtoStudent student = 6;</code>
     */
    public int getStudentCount() {
      if (studentBuilder_ == null) {
        return student_.size();
      } else {
        return studentBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .tutorial.ProtoStudent student = 6;</code>
     */
    public uc.mei.is.ProtoStudent getStudent(int index) {
      if (studentBuilder_ == null) {
        return student_.get(index);
      } else {
        return studentBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .tutorial.ProtoStudent student = 6;</code>
     */
    public Builder setStudent(
        int index, uc.mei.is.ProtoStudent value) {
      if (studentBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureStudentIsMutable();
        student_.set(index, value);
        onChanged();
      } else {
        studentBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .tutorial.ProtoStudent student = 6;</code>
     */
    public Builder setStudent(
        int index, uc.mei.is.ProtoStudent.Builder builderForValue) {
      if (studentBuilder_ == null) {
        ensureStudentIsMutable();
        student_.set(index, builderForValue.build());
        onChanged();
      } else {
        studentBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .tutorial.ProtoStudent student = 6;</code>
     */
    public Builder addStudent(uc.mei.is.ProtoStudent value) {
      if (studentBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureStudentIsMutable();
        student_.add(value);
        onChanged();
      } else {
        studentBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .tutorial.ProtoStudent student = 6;</code>
     */
    public Builder addStudent(
        int index, uc.mei.is.ProtoStudent value) {
      if (studentBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureStudentIsMutable();
        student_.add(index, value);
        onChanged();
      } else {
        studentBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .tutorial.ProtoStudent student = 6;</code>
     */
    public Builder addStudent(
        uc.mei.is.ProtoStudent.Builder builderForValue) {
      if (studentBuilder_ == null) {
        ensureStudentIsMutable();
        student_.add(builderForValue.build());
        onChanged();
      } else {
        studentBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .tutorial.ProtoStudent student = 6;</code>
     */
    public Builder addStudent(
        int index, uc.mei.is.ProtoStudent.Builder builderForValue) {
      if (studentBuilder_ == null) {
        ensureStudentIsMutable();
        student_.add(index, builderForValue.build());
        onChanged();
      } else {
        studentBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .tutorial.ProtoStudent student = 6;</code>
     */
    public Builder addAllStudent(
        java.lang.Iterable<? extends uc.mei.is.ProtoStudent> values) {
      if (studentBuilder_ == null) {
        ensureStudentIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, student_);
        onChanged();
      } else {
        studentBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .tutorial.ProtoStudent student = 6;</code>
     */
    public Builder clearStudent() {
      if (studentBuilder_ == null) {
        student_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000020);
        onChanged();
      } else {
        studentBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .tutorial.ProtoStudent student = 6;</code>
     */
    public Builder removeStudent(int index) {
      if (studentBuilder_ == null) {
        ensureStudentIsMutable();
        student_.remove(index);
        onChanged();
      } else {
        studentBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .tutorial.ProtoStudent student = 6;</code>
     */
    public uc.mei.is.ProtoStudent.Builder getStudentBuilder(
        int index) {
      return getStudentFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .tutorial.ProtoStudent student = 6;</code>
     */
    public uc.mei.is.ProtoStudentOrBuilder getStudentOrBuilder(
        int index) {
      if (studentBuilder_ == null) {
        return student_.get(index);  } else {
        return studentBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .tutorial.ProtoStudent student = 6;</code>
     */
    public java.util.List<? extends uc.mei.is.ProtoStudentOrBuilder> 
         getStudentOrBuilderList() {
      if (studentBuilder_ != null) {
        return studentBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(student_);
      }
    }
    /**
     * <code>repeated .tutorial.ProtoStudent student = 6;</code>
     */
    public uc.mei.is.ProtoStudent.Builder addStudentBuilder() {
      return getStudentFieldBuilder().addBuilder(
          uc.mei.is.ProtoStudent.getDefaultInstance());
    }
    /**
     * <code>repeated .tutorial.ProtoStudent student = 6;</code>
     */
    public uc.mei.is.ProtoStudent.Builder addStudentBuilder(
        int index) {
      return getStudentFieldBuilder().addBuilder(
          index, uc.mei.is.ProtoStudent.getDefaultInstance());
    }
    /**
     * <code>repeated .tutorial.ProtoStudent student = 6;</code>
     */
    public java.util.List<uc.mei.is.ProtoStudent.Builder> 
         getStudentBuilderList() {
      return getStudentFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        uc.mei.is.ProtoStudent, uc.mei.is.ProtoStudent.Builder, uc.mei.is.ProtoStudentOrBuilder> 
        getStudentFieldBuilder() {
      if (studentBuilder_ == null) {
        studentBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            uc.mei.is.ProtoStudent, uc.mei.is.ProtoStudent.Builder, uc.mei.is.ProtoStudentOrBuilder>(
                student_,
                ((bitField0_ & 0x00000020) != 0),
                getParentForChildren(),
                isClean());
        student_ = null;
      }
      return studentBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:tutorial.ProtoProfessor)
  }

  // @@protoc_insertion_point(class_scope:tutorial.ProtoProfessor)
  private static final uc.mei.is.ProtoProfessor DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new uc.mei.is.ProtoProfessor();
  }

  public static uc.mei.is.ProtoProfessor getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ProtoProfessor>
      PARSER = new com.google.protobuf.AbstractParser<ProtoProfessor>() {
    @java.lang.Override
    public ProtoProfessor parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ProtoProfessor(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ProtoProfessor> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ProtoProfessor> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public uc.mei.is.ProtoProfessor getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

