// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: App.proto

package uc.mei.is;

public final class ProtoApp {
  private ProtoApp() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tutorial_ProtoStudent_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tutorial_ProtoStudent_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tutorial_ProtoProfessor_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tutorial_ProtoProfessor_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tutorial_ProtoProfList_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tutorial_ProtoProfList_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\tApp.proto\022\010tutorial\032\037google/protobuf/t" +
      "imestamp.proto\"\322\002\n\014ProtoStudent\022\021\n\004uuid\030" +
      "\001 \001(\tH\000\210\001\001\022\021\n\004name\030\002 \001(\tH\001\210\001\001\022\025\n\010phoneNu" +
      "m\030\003 \001(\tH\002\210\001\001\022\021\n\004addr\030\004 \001(\tH\003\210\001\001\022-\n\004bday\030" +
      "\005 \001(\0132\032.google.protobuf.TimestampH\004\210\001\001\022\025" +
      "\n\010profuuid\030\006 \001(\tH\005\210\001\001\022\023\n\006gender\030\007 \001(\tH\006\210" +
      "\001\001\0229\n\020registrationDate\030\010 \001(\0132\032.google.pr" +
      "otobuf.TimestampH\007\210\001\001B\007\n\005_uuidB\007\n\005_nameB" +
      "\013\n\t_phoneNumB\007\n\005_addrB\007\n\005_bdayB\013\n\t_profu" +
      "uidB\t\n\007_genderB\023\n\021_registrationDate\"\351\001\n\016" +
      "ProtoProfessor\022\021\n\004uuid\030\001 \001(\tH\000\210\001\001\022\021\n\004nam" +
      "e\030\002 \001(\tH\001\210\001\001\022\025\n\010phoneNum\030\003 \001(\tH\002\210\001\001\022\021\n\004a" +
      "ddr\030\004 \001(\tH\003\210\001\001\022-\n\004bday\030\005 \001(\0132\032.google.pr" +
      "otobuf.TimestampH\004\210\001\001\022\'\n\007student\030\006 \003(\0132\026" +
      ".tutorial.ProtoStudentB\007\n\005_uuidB\007\n\005_name" +
      "B\013\n\t_phoneNumB\007\n\005_addrB\007\n\005_bday\"<\n\rProto" +
      "ProfList\022+\n\tprofessor\030\001 \003(\0132\030.tutorial.P" +
      "rotoProfessorB\027\n\tuc.mei.isB\010ProtoAppP\001b\006" +
      "proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.TimestampProto.getDescriptor(),
        });
    internal_static_tutorial_ProtoStudent_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_tutorial_ProtoStudent_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tutorial_ProtoStudent_descriptor,
        new java.lang.String[] { "Uuid", "Name", "PhoneNum", "Addr", "Bday", "Profuuid", "Gender", "RegistrationDate", "Uuid", "Name", "PhoneNum", "Addr", "Bday", "Profuuid", "Gender", "RegistrationDate", });
    internal_static_tutorial_ProtoProfessor_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_tutorial_ProtoProfessor_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tutorial_ProtoProfessor_descriptor,
        new java.lang.String[] { "Uuid", "Name", "PhoneNum", "Addr", "Bday", "Student", "Uuid", "Name", "PhoneNum", "Addr", "Bday", });
    internal_static_tutorial_ProtoProfList_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_tutorial_ProtoProfList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tutorial_ProtoProfList_descriptor,
        new java.lang.String[] { "Professor", });
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
