// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: App.proto

package uc.mei.is;

/**
 * Protobuf type {@code tutorial.ProtoStudent}
 */
public final class ProtoStudent extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:tutorial.ProtoStudent)
    ProtoStudentOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ProtoStudent.newBuilder() to construct.
  private ProtoStudent(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ProtoStudent() {
    uuid_ = "";
    name_ = "";
    phoneNum_ = "";
    addr_ = "";
    profuuid_ = "";
    gender_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ProtoStudent();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ProtoStudent(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();
            bitField0_ |= 0x00000001;
            uuid_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();
            bitField0_ |= 0x00000002;
            name_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();
            bitField0_ |= 0x00000004;
            phoneNum_ = s;
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();
            bitField0_ |= 0x00000008;
            addr_ = s;
            break;
          }
          case 42: {
            com.google.protobuf.Timestamp.Builder subBuilder = null;
            if (((bitField0_ & 0x00000010) != 0)) {
              subBuilder = bday_.toBuilder();
            }
            bday_ = input.readMessage(com.google.protobuf.Timestamp.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(bday_);
              bday_ = subBuilder.buildPartial();
            }
            bitField0_ |= 0x00000010;
            break;
          }
          case 50: {
            java.lang.String s = input.readStringRequireUtf8();
            bitField0_ |= 0x00000020;
            profuuid_ = s;
            break;
          }
          case 58: {
            java.lang.String s = input.readStringRequireUtf8();
            bitField0_ |= 0x00000040;
            gender_ = s;
            break;
          }
          case 66: {
            com.google.protobuf.Timestamp.Builder subBuilder = null;
            if (((bitField0_ & 0x00000080) != 0)) {
              subBuilder = registrationDate_.toBuilder();
            }
            registrationDate_ = input.readMessage(com.google.protobuf.Timestamp.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(registrationDate_);
              registrationDate_ = subBuilder.buildPartial();
            }
            bitField0_ |= 0x00000080;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (com.google.protobuf.UninitializedMessageException e) {
      throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return uc.mei.is.ProtoApp.internal_static_tutorial_ProtoStudent_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return uc.mei.is.ProtoApp.internal_static_tutorial_ProtoStudent_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            uc.mei.is.ProtoStudent.class, uc.mei.is.ProtoStudent.Builder.class);
  }

  private int bitField0_;
  public static final int UUID_FIELD_NUMBER = 1;
  private volatile java.lang.Object uuid_;
  /**
   * <code>optional string uuid = 1;</code>
   * @return Whether the uuid field is set.
   */
  @java.lang.Override
  public boolean hasUuid() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>optional string uuid = 1;</code>
   * @return The uuid.
   */
  @java.lang.Override
  public java.lang.String getUuid() {
    java.lang.Object ref = uuid_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      uuid_ = s;
      return s;
    }
  }
  /**
   * <code>optional string uuid = 1;</code>
   * @return The bytes for uuid.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getUuidBytes() {
    java.lang.Object ref = uuid_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      uuid_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int NAME_FIELD_NUMBER = 2;
  private volatile java.lang.Object name_;
  /**
   * <code>optional string name = 2;</code>
   * @return Whether the name field is set.
   */
  @java.lang.Override
  public boolean hasName() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>optional string name = 2;</code>
   * @return The name.
   */
  @java.lang.Override
  public java.lang.String getName() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      name_ = s;
      return s;
    }
  }
  /**
   * <code>optional string name = 2;</code>
   * @return The bytes for name.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNameBytes() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PHONENUM_FIELD_NUMBER = 3;
  private volatile java.lang.Object phoneNum_;
  /**
   * <code>optional string phoneNum = 3;</code>
   * @return Whether the phoneNum field is set.
   */
  @java.lang.Override
  public boolean hasPhoneNum() {
    return ((bitField0_ & 0x00000004) != 0);
  }
  /**
   * <code>optional string phoneNum = 3;</code>
   * @return The phoneNum.
   */
  @java.lang.Override
  public java.lang.String getPhoneNum() {
    java.lang.Object ref = phoneNum_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      phoneNum_ = s;
      return s;
    }
  }
  /**
   * <code>optional string phoneNum = 3;</code>
   * @return The bytes for phoneNum.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getPhoneNumBytes() {
    java.lang.Object ref = phoneNum_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      phoneNum_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ADDR_FIELD_NUMBER = 4;
  private volatile java.lang.Object addr_;
  /**
   * <code>optional string addr = 4;</code>
   * @return Whether the addr field is set.
   */
  @java.lang.Override
  public boolean hasAddr() {
    return ((bitField0_ & 0x00000008) != 0);
  }
  /**
   * <code>optional string addr = 4;</code>
   * @return The addr.
   */
  @java.lang.Override
  public java.lang.String getAddr() {
    java.lang.Object ref = addr_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      addr_ = s;
      return s;
    }
  }
  /**
   * <code>optional string addr = 4;</code>
   * @return The bytes for addr.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getAddrBytes() {
    java.lang.Object ref = addr_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      addr_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int BDAY_FIELD_NUMBER = 5;
  private com.google.protobuf.Timestamp bday_;
  /**
   * <code>optional .google.protobuf.Timestamp bday = 5;</code>
   * @return Whether the bday field is set.
   */
  @java.lang.Override
  public boolean hasBday() {
    return ((bitField0_ & 0x00000010) != 0);
  }
  /**
   * <code>optional .google.protobuf.Timestamp bday = 5;</code>
   * @return The bday.
   */
  @java.lang.Override
  public com.google.protobuf.Timestamp getBday() {
    return bday_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : bday_;
  }
  /**
   * <code>optional .google.protobuf.Timestamp bday = 5;</code>
   */
  @java.lang.Override
  public com.google.protobuf.TimestampOrBuilder getBdayOrBuilder() {
    return bday_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : bday_;
  }

  public static final int PROFUUID_FIELD_NUMBER = 6;
  private volatile java.lang.Object profuuid_;
  /**
   * <code>optional string profuuid = 6;</code>
   * @return Whether the profuuid field is set.
   */
  @java.lang.Override
  public boolean hasProfuuid() {
    return ((bitField0_ & 0x00000020) != 0);
  }
  /**
   * <code>optional string profuuid = 6;</code>
   * @return The profuuid.
   */
  @java.lang.Override
  public java.lang.String getProfuuid() {
    java.lang.Object ref = profuuid_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      profuuid_ = s;
      return s;
    }
  }
  /**
   * <code>optional string profuuid = 6;</code>
   * @return The bytes for profuuid.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getProfuuidBytes() {
    java.lang.Object ref = profuuid_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      profuuid_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int GENDER_FIELD_NUMBER = 7;
  private volatile java.lang.Object gender_;
  /**
   * <code>optional string gender = 7;</code>
   * @return Whether the gender field is set.
   */
  @java.lang.Override
  public boolean hasGender() {
    return ((bitField0_ & 0x00000040) != 0);
  }
  /**
   * <code>optional string gender = 7;</code>
   * @return The gender.
   */
  @java.lang.Override
  public java.lang.String getGender() {
    java.lang.Object ref = gender_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      gender_ = s;
      return s;
    }
  }
  /**
   * <code>optional string gender = 7;</code>
   * @return The bytes for gender.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getGenderBytes() {
    java.lang.Object ref = gender_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      gender_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int REGISTRATIONDATE_FIELD_NUMBER = 8;
  private com.google.protobuf.Timestamp registrationDate_;
  /**
   * <code>optional .google.protobuf.Timestamp registrationDate = 8;</code>
   * @return Whether the registrationDate field is set.
   */
  @java.lang.Override
  public boolean hasRegistrationDate() {
    return ((bitField0_ & 0x00000080) != 0);
  }
  /**
   * <code>optional .google.protobuf.Timestamp registrationDate = 8;</code>
   * @return The registrationDate.
   */
  @java.lang.Override
  public com.google.protobuf.Timestamp getRegistrationDate() {
    return registrationDate_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : registrationDate_;
  }
  /**
   * <code>optional .google.protobuf.Timestamp registrationDate = 8;</code>
   */
  @java.lang.Override
  public com.google.protobuf.TimestampOrBuilder getRegistrationDateOrBuilder() {
    return registrationDate_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : registrationDate_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, uuid_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, phoneNum_);
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, addr_);
    }
    if (((bitField0_ & 0x00000010) != 0)) {
      output.writeMessage(5, getBday());
    }
    if (((bitField0_ & 0x00000020) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, profuuid_);
    }
    if (((bitField0_ & 0x00000040) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 7, gender_);
    }
    if (((bitField0_ & 0x00000080) != 0)) {
      output.writeMessage(8, getRegistrationDate());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, uuid_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, phoneNum_);
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, addr_);
    }
    if (((bitField0_ & 0x00000010) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, getBday());
    }
    if (((bitField0_ & 0x00000020) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, profuuid_);
    }
    if (((bitField0_ & 0x00000040) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, gender_);
    }
    if (((bitField0_ & 0x00000080) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(8, getRegistrationDate());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof uc.mei.is.ProtoStudent)) {
      return super.equals(obj);
    }
    uc.mei.is.ProtoStudent other = (uc.mei.is.ProtoStudent) obj;

    if (hasUuid() != other.hasUuid()) return false;
    if (hasUuid()) {
      if (!getUuid()
          .equals(other.getUuid())) return false;
    }
    if (hasName() != other.hasName()) return false;
    if (hasName()) {
      if (!getName()
          .equals(other.getName())) return false;
    }
    if (hasPhoneNum() != other.hasPhoneNum()) return false;
    if (hasPhoneNum()) {
      if (!getPhoneNum()
          .equals(other.getPhoneNum())) return false;
    }
    if (hasAddr() != other.hasAddr()) return false;
    if (hasAddr()) {
      if (!getAddr()
          .equals(other.getAddr())) return false;
    }
    if (hasBday() != other.hasBday()) return false;
    if (hasBday()) {
      if (!getBday()
          .equals(other.getBday())) return false;
    }
    if (hasProfuuid() != other.hasProfuuid()) return false;
    if (hasProfuuid()) {
      if (!getProfuuid()
          .equals(other.getProfuuid())) return false;
    }
    if (hasGender() != other.hasGender()) return false;
    if (hasGender()) {
      if (!getGender()
          .equals(other.getGender())) return false;
    }
    if (hasRegistrationDate() != other.hasRegistrationDate()) return false;
    if (hasRegistrationDate()) {
      if (!getRegistrationDate()
          .equals(other.getRegistrationDate())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasUuid()) {
      hash = (37 * hash) + UUID_FIELD_NUMBER;
      hash = (53 * hash) + getUuid().hashCode();
    }
    if (hasName()) {
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
    }
    if (hasPhoneNum()) {
      hash = (37 * hash) + PHONENUM_FIELD_NUMBER;
      hash = (53 * hash) + getPhoneNum().hashCode();
    }
    if (hasAddr()) {
      hash = (37 * hash) + ADDR_FIELD_NUMBER;
      hash = (53 * hash) + getAddr().hashCode();
    }
    if (hasBday()) {
      hash = (37 * hash) + BDAY_FIELD_NUMBER;
      hash = (53 * hash) + getBday().hashCode();
    }
    if (hasProfuuid()) {
      hash = (37 * hash) + PROFUUID_FIELD_NUMBER;
      hash = (53 * hash) + getProfuuid().hashCode();
    }
    if (hasGender()) {
      hash = (37 * hash) + GENDER_FIELD_NUMBER;
      hash = (53 * hash) + getGender().hashCode();
    }
    if (hasRegistrationDate()) {
      hash = (37 * hash) + REGISTRATIONDATE_FIELD_NUMBER;
      hash = (53 * hash) + getRegistrationDate().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static uc.mei.is.ProtoStudent parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static uc.mei.is.ProtoStudent parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static uc.mei.is.ProtoStudent parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static uc.mei.is.ProtoStudent parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static uc.mei.is.ProtoStudent parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static uc.mei.is.ProtoStudent parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static uc.mei.is.ProtoStudent parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static uc.mei.is.ProtoStudent parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static uc.mei.is.ProtoStudent parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static uc.mei.is.ProtoStudent parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static uc.mei.is.ProtoStudent parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static uc.mei.is.ProtoStudent parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(uc.mei.is.ProtoStudent prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code tutorial.ProtoStudent}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:tutorial.ProtoStudent)
      uc.mei.is.ProtoStudentOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return uc.mei.is.ProtoApp.internal_static_tutorial_ProtoStudent_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return uc.mei.is.ProtoApp.internal_static_tutorial_ProtoStudent_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              uc.mei.is.ProtoStudent.class, uc.mei.is.ProtoStudent.Builder.class);
    }

    // Construct using uc.mei.is.ProtoStudent.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getBdayFieldBuilder();
        getRegistrationDateFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      uuid_ = "";
      bitField0_ = (bitField0_ & ~0x00000001);
      name_ = "";
      bitField0_ = (bitField0_ & ~0x00000002);
      phoneNum_ = "";
      bitField0_ = (bitField0_ & ~0x00000004);
      addr_ = "";
      bitField0_ = (bitField0_ & ~0x00000008);
      if (bdayBuilder_ == null) {
        bday_ = null;
      } else {
        bdayBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000010);
      profuuid_ = "";
      bitField0_ = (bitField0_ & ~0x00000020);
      gender_ = "";
      bitField0_ = (bitField0_ & ~0x00000040);
      if (registrationDateBuilder_ == null) {
        registrationDate_ = null;
      } else {
        registrationDateBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000080);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return uc.mei.is.ProtoApp.internal_static_tutorial_ProtoStudent_descriptor;
    }

    @java.lang.Override
    public uc.mei.is.ProtoStudent getDefaultInstanceForType() {
      return uc.mei.is.ProtoStudent.getDefaultInstance();
    }

    @java.lang.Override
    public uc.mei.is.ProtoStudent build() {
      uc.mei.is.ProtoStudent result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public uc.mei.is.ProtoStudent buildPartial() {
      uc.mei.is.ProtoStudent result = new uc.mei.is.ProtoStudent(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        to_bitField0_ |= 0x00000001;
      }
      result.uuid_ = uuid_;
      if (((from_bitField0_ & 0x00000002) != 0)) {
        to_bitField0_ |= 0x00000002;
      }
      result.name_ = name_;
      if (((from_bitField0_ & 0x00000004) != 0)) {
        to_bitField0_ |= 0x00000004;
      }
      result.phoneNum_ = phoneNum_;
      if (((from_bitField0_ & 0x00000008) != 0)) {
        to_bitField0_ |= 0x00000008;
      }
      result.addr_ = addr_;
      if (((from_bitField0_ & 0x00000010) != 0)) {
        if (bdayBuilder_ == null) {
          result.bday_ = bday_;
        } else {
          result.bday_ = bdayBuilder_.build();
        }
        to_bitField0_ |= 0x00000010;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        to_bitField0_ |= 0x00000020;
      }
      result.profuuid_ = profuuid_;
      if (((from_bitField0_ & 0x00000040) != 0)) {
        to_bitField0_ |= 0x00000040;
      }
      result.gender_ = gender_;
      if (((from_bitField0_ & 0x00000080) != 0)) {
        if (registrationDateBuilder_ == null) {
          result.registrationDate_ = registrationDate_;
        } else {
          result.registrationDate_ = registrationDateBuilder_.build();
        }
        to_bitField0_ |= 0x00000080;
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof uc.mei.is.ProtoStudent) {
        return mergeFrom((uc.mei.is.ProtoStudent)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(uc.mei.is.ProtoStudent other) {
      if (other == uc.mei.is.ProtoStudent.getDefaultInstance()) return this;
      if (other.hasUuid()) {
        bitField0_ |= 0x00000001;
        uuid_ = other.uuid_;
        onChanged();
      }
      if (other.hasName()) {
        bitField0_ |= 0x00000002;
        name_ = other.name_;
        onChanged();
      }
      if (other.hasPhoneNum()) {
        bitField0_ |= 0x00000004;
        phoneNum_ = other.phoneNum_;
        onChanged();
      }
      if (other.hasAddr()) {
        bitField0_ |= 0x00000008;
        addr_ = other.addr_;
        onChanged();
      }
      if (other.hasBday()) {
        mergeBday(other.getBday());
      }
      if (other.hasProfuuid()) {
        bitField0_ |= 0x00000020;
        profuuid_ = other.profuuid_;
        onChanged();
      }
      if (other.hasGender()) {
        bitField0_ |= 0x00000040;
        gender_ = other.gender_;
        onChanged();
      }
      if (other.hasRegistrationDate()) {
        mergeRegistrationDate(other.getRegistrationDate());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      uc.mei.is.ProtoStudent parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (uc.mei.is.ProtoStudent) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.lang.Object uuid_ = "";
    /**
     * <code>optional string uuid = 1;</code>
     * @return Whether the uuid field is set.
     */
    public boolean hasUuid() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional string uuid = 1;</code>
     * @return The uuid.
     */
    public java.lang.String getUuid() {
      java.lang.Object ref = uuid_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        uuid_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string uuid = 1;</code>
     * @return The bytes for uuid.
     */
    public com.google.protobuf.ByteString
        getUuidBytes() {
      java.lang.Object ref = uuid_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        uuid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string uuid = 1;</code>
     * @param value The uuid to set.
     * @return This builder for chaining.
     */
    public Builder setUuid(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
      uuid_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string uuid = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearUuid() {
      bitField0_ = (bitField0_ & ~0x00000001);
      uuid_ = getDefaultInstance().getUuid();
      onChanged();
      return this;
    }
    /**
     * <code>optional string uuid = 1;</code>
     * @param value The bytes for uuid to set.
     * @return This builder for chaining.
     */
    public Builder setUuidBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      bitField0_ |= 0x00000001;
      uuid_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object name_ = "";
    /**
     * <code>optional string name = 2;</code>
     * @return Whether the name field is set.
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional string name = 2;</code>
     * @return The name.
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string name = 2;</code>
     * @return The bytes for name.
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string name = 2;</code>
     * @param value The name to set.
     * @return This builder for chaining.
     */
    public Builder setName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
      name_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string name = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearName() {
      bitField0_ = (bitField0_ & ~0x00000002);
      name_ = getDefaultInstance().getName();
      onChanged();
      return this;
    }
    /**
     * <code>optional string name = 2;</code>
     * @param value The bytes for name to set.
     * @return This builder for chaining.
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      bitField0_ |= 0x00000002;
      name_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object phoneNum_ = "";
    /**
     * <code>optional string phoneNum = 3;</code>
     * @return Whether the phoneNum field is set.
     */
    public boolean hasPhoneNum() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional string phoneNum = 3;</code>
     * @return The phoneNum.
     */
    public java.lang.String getPhoneNum() {
      java.lang.Object ref = phoneNum_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        phoneNum_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string phoneNum = 3;</code>
     * @return The bytes for phoneNum.
     */
    public com.google.protobuf.ByteString
        getPhoneNumBytes() {
      java.lang.Object ref = phoneNum_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        phoneNum_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string phoneNum = 3;</code>
     * @param value The phoneNum to set.
     * @return This builder for chaining.
     */
    public Builder setPhoneNum(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
      phoneNum_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string phoneNum = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearPhoneNum() {
      bitField0_ = (bitField0_ & ~0x00000004);
      phoneNum_ = getDefaultInstance().getPhoneNum();
      onChanged();
      return this;
    }
    /**
     * <code>optional string phoneNum = 3;</code>
     * @param value The bytes for phoneNum to set.
     * @return This builder for chaining.
     */
    public Builder setPhoneNumBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      bitField0_ |= 0x00000004;
      phoneNum_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object addr_ = "";
    /**
     * <code>optional string addr = 4;</code>
     * @return Whether the addr field is set.
     */
    public boolean hasAddr() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>optional string addr = 4;</code>
     * @return The addr.
     */
    public java.lang.String getAddr() {
      java.lang.Object ref = addr_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        addr_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string addr = 4;</code>
     * @return The bytes for addr.
     */
    public com.google.protobuf.ByteString
        getAddrBytes() {
      java.lang.Object ref = addr_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        addr_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string addr = 4;</code>
     * @param value The addr to set.
     * @return This builder for chaining.
     */
    public Builder setAddr(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
      addr_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string addr = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearAddr() {
      bitField0_ = (bitField0_ & ~0x00000008);
      addr_ = getDefaultInstance().getAddr();
      onChanged();
      return this;
    }
    /**
     * <code>optional string addr = 4;</code>
     * @param value The bytes for addr to set.
     * @return This builder for chaining.
     */
    public Builder setAddrBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      bitField0_ |= 0x00000008;
      addr_ = value;
      onChanged();
      return this;
    }

    private com.google.protobuf.Timestamp bday_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> bdayBuilder_;
    /**
     * <code>optional .google.protobuf.Timestamp bday = 5;</code>
     * @return Whether the bday field is set.
     */
    public boolean hasBday() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <code>optional .google.protobuf.Timestamp bday = 5;</code>
     * @return The bday.
     */
    public com.google.protobuf.Timestamp getBday() {
      if (bdayBuilder_ == null) {
        return bday_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : bday_;
      } else {
        return bdayBuilder_.getMessage();
      }
    }
    /**
     * <code>optional .google.protobuf.Timestamp bday = 5;</code>
     */
    public Builder setBday(com.google.protobuf.Timestamp value) {
      if (bdayBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        bday_ = value;
        onChanged();
      } else {
        bdayBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000010;
      return this;
    }
    /**
     * <code>optional .google.protobuf.Timestamp bday = 5;</code>
     */
    public Builder setBday(
        com.google.protobuf.Timestamp.Builder builderForValue) {
      if (bdayBuilder_ == null) {
        bday_ = builderForValue.build();
        onChanged();
      } else {
        bdayBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000010;
      return this;
    }
    /**
     * <code>optional .google.protobuf.Timestamp bday = 5;</code>
     */
    public Builder mergeBday(com.google.protobuf.Timestamp value) {
      if (bdayBuilder_ == null) {
        if (((bitField0_ & 0x00000010) != 0) &&
            bday_ != null &&
            bday_ != com.google.protobuf.Timestamp.getDefaultInstance()) {
          bday_ =
            com.google.protobuf.Timestamp.newBuilder(bday_).mergeFrom(value).buildPartial();
        } else {
          bday_ = value;
        }
        onChanged();
      } else {
        bdayBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000010;
      return this;
    }
    /**
     * <code>optional .google.protobuf.Timestamp bday = 5;</code>
     */
    public Builder clearBday() {
      if (bdayBuilder_ == null) {
        bday_ = null;
        onChanged();
      } else {
        bdayBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000010);
      return this;
    }
    /**
     * <code>optional .google.protobuf.Timestamp bday = 5;</code>
     */
    public com.google.protobuf.Timestamp.Builder getBdayBuilder() {
      bitField0_ |= 0x00000010;
      onChanged();
      return getBdayFieldBuilder().getBuilder();
    }
    /**
     * <code>optional .google.protobuf.Timestamp bday = 5;</code>
     */
    public com.google.protobuf.TimestampOrBuilder getBdayOrBuilder() {
      if (bdayBuilder_ != null) {
        return bdayBuilder_.getMessageOrBuilder();
      } else {
        return bday_ == null ?
            com.google.protobuf.Timestamp.getDefaultInstance() : bday_;
      }
    }
    /**
     * <code>optional .google.protobuf.Timestamp bday = 5;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
        getBdayFieldBuilder() {
      if (bdayBuilder_ == null) {
        bdayBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                getBday(),
                getParentForChildren(),
                isClean());
        bday_ = null;
      }
      return bdayBuilder_;
    }

    private java.lang.Object profuuid_ = "";
    /**
     * <code>optional string profuuid = 6;</code>
     * @return Whether the profuuid field is set.
     */
    public boolean hasProfuuid() {
      return ((bitField0_ & 0x00000020) != 0);
    }
    /**
     * <code>optional string profuuid = 6;</code>
     * @return The profuuid.
     */
    public java.lang.String getProfuuid() {
      java.lang.Object ref = profuuid_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        profuuid_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string profuuid = 6;</code>
     * @return The bytes for profuuid.
     */
    public com.google.protobuf.ByteString
        getProfuuidBytes() {
      java.lang.Object ref = profuuid_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        profuuid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string profuuid = 6;</code>
     * @param value The profuuid to set.
     * @return This builder for chaining.
     */
    public Builder setProfuuid(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
      profuuid_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string profuuid = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearProfuuid() {
      bitField0_ = (bitField0_ & ~0x00000020);
      profuuid_ = getDefaultInstance().getProfuuid();
      onChanged();
      return this;
    }
    /**
     * <code>optional string profuuid = 6;</code>
     * @param value The bytes for profuuid to set.
     * @return This builder for chaining.
     */
    public Builder setProfuuidBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      bitField0_ |= 0x00000020;
      profuuid_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object gender_ = "";
    /**
     * <code>optional string gender = 7;</code>
     * @return Whether the gender field is set.
     */
    public boolean hasGender() {
      return ((bitField0_ & 0x00000040) != 0);
    }
    /**
     * <code>optional string gender = 7;</code>
     * @return The gender.
     */
    public java.lang.String getGender() {
      java.lang.Object ref = gender_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        gender_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string gender = 7;</code>
     * @return The bytes for gender.
     */
    public com.google.protobuf.ByteString
        getGenderBytes() {
      java.lang.Object ref = gender_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        gender_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string gender = 7;</code>
     * @param value The gender to set.
     * @return This builder for chaining.
     */
    public Builder setGender(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
      gender_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string gender = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearGender() {
      bitField0_ = (bitField0_ & ~0x00000040);
      gender_ = getDefaultInstance().getGender();
      onChanged();
      return this;
    }
    /**
     * <code>optional string gender = 7;</code>
     * @param value The bytes for gender to set.
     * @return This builder for chaining.
     */
    public Builder setGenderBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      bitField0_ |= 0x00000040;
      gender_ = value;
      onChanged();
      return this;
    }

    private com.google.protobuf.Timestamp registrationDate_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> registrationDateBuilder_;
    /**
     * <code>optional .google.protobuf.Timestamp registrationDate = 8;</code>
     * @return Whether the registrationDate field is set.
     */
    public boolean hasRegistrationDate() {
      return ((bitField0_ & 0x00000080) != 0);
    }
    /**
     * <code>optional .google.protobuf.Timestamp registrationDate = 8;</code>
     * @return The registrationDate.
     */
    public com.google.protobuf.Timestamp getRegistrationDate() {
      if (registrationDateBuilder_ == null) {
        return registrationDate_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : registrationDate_;
      } else {
        return registrationDateBuilder_.getMessage();
      }
    }
    /**
     * <code>optional .google.protobuf.Timestamp registrationDate = 8;</code>
     */
    public Builder setRegistrationDate(com.google.protobuf.Timestamp value) {
      if (registrationDateBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        registrationDate_ = value;
        onChanged();
      } else {
        registrationDateBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000080;
      return this;
    }
    /**
     * <code>optional .google.protobuf.Timestamp registrationDate = 8;</code>
     */
    public Builder setRegistrationDate(
        com.google.protobuf.Timestamp.Builder builderForValue) {
      if (registrationDateBuilder_ == null) {
        registrationDate_ = builderForValue.build();
        onChanged();
      } else {
        registrationDateBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000080;
      return this;
    }
    /**
     * <code>optional .google.protobuf.Timestamp registrationDate = 8;</code>
     */
    public Builder mergeRegistrationDate(com.google.protobuf.Timestamp value) {
      if (registrationDateBuilder_ == null) {
        if (((bitField0_ & 0x00000080) != 0) &&
            registrationDate_ != null &&
            registrationDate_ != com.google.protobuf.Timestamp.getDefaultInstance()) {
          registrationDate_ =
            com.google.protobuf.Timestamp.newBuilder(registrationDate_).mergeFrom(value).buildPartial();
        } else {
          registrationDate_ = value;
        }
        onChanged();
      } else {
        registrationDateBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000080;
      return this;
    }
    /**
     * <code>optional .google.protobuf.Timestamp registrationDate = 8;</code>
     */
    public Builder clearRegistrationDate() {
      if (registrationDateBuilder_ == null) {
        registrationDate_ = null;
        onChanged();
      } else {
        registrationDateBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000080);
      return this;
    }
    /**
     * <code>optional .google.protobuf.Timestamp registrationDate = 8;</code>
     */
    public com.google.protobuf.Timestamp.Builder getRegistrationDateBuilder() {
      bitField0_ |= 0x00000080;
      onChanged();
      return getRegistrationDateFieldBuilder().getBuilder();
    }
    /**
     * <code>optional .google.protobuf.Timestamp registrationDate = 8;</code>
     */
    public com.google.protobuf.TimestampOrBuilder getRegistrationDateOrBuilder() {
      if (registrationDateBuilder_ != null) {
        return registrationDateBuilder_.getMessageOrBuilder();
      } else {
        return registrationDate_ == null ?
            com.google.protobuf.Timestamp.getDefaultInstance() : registrationDate_;
      }
    }
    /**
     * <code>optional .google.protobuf.Timestamp registrationDate = 8;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
        getRegistrationDateFieldBuilder() {
      if (registrationDateBuilder_ == null) {
        registrationDateBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                getRegistrationDate(),
                getParentForChildren(),
                isClean());
        registrationDate_ = null;
      }
      return registrationDateBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:tutorial.ProtoStudent)
  }

  // @@protoc_insertion_point(class_scope:tutorial.ProtoStudent)
  private static final uc.mei.is.ProtoStudent DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new uc.mei.is.ProtoStudent();
  }

  public static uc.mei.is.ProtoStudent getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ProtoStudent>
      PARSER = new com.google.protobuf.AbstractParser<ProtoStudent>() {
    @java.lang.Override
    public ProtoStudent parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ProtoStudent(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ProtoStudent> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ProtoStudent> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public uc.mei.is.ProtoStudent getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

